version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: crud-backend
    container_name: crud-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - crud-network
    command: npm run dev

networks:
  crud-network:
    name: crud-network
    driver: bridge
