apiVersion: v1
kind: Service
metadata:
  name: crud-backend-service
spec:
  type: NodePort
  selector:
    app: crud-backend  # Change this to match your pod labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 30080